const ar: Record<string, string> = {
  cart: 'العربة',
  cartEmpty: 'سلتك فارغة',
  startShopping: 'استمر في التسوق',
  subtotal: 'المجموع الفرعي',
  shipping: 'الشحن',
  free: 'مجاناً',
  total: 'الإجمالي',
  checkout: 'إتمام الطلب',
  remove: 'حذف',
  quantity: 'الكمية',
  addToCart: 'أضف إلى العربة',
  buyNow: 'شراء الآن',
  favorites: 'المفضلة',
  search: 'بحث',
  profile: 'الملف الشخصي',
  orders: 'طلباتي',
  orderDetails: 'تفاصيل الطلب',
  orderStatus: 'حالة الطلب',
  orderDate: 'تاريخ الطلب',
  orderTotal: 'إجمالي الطلب',
  paymentMethod: 'طريقة الدفع',
  cashOnDelivery: 'الدفع عند الاستلام',
  creditCard: 'بطاقة ائتمان',
  wallet: 'المحفظة الإلكترونية',
  transferReceipt: 'تحويل بنكي (إيصال)',
  couponCode: 'كود الخصم',
  apply: 'تطبيق',
  invalidCoupon: 'كود خصم غير صالح',
  validCoupon: 'تم تطبيق الخصم',
  discount: 'الخصم',
  fullName: 'الاسم الكامل',
  phone: 'رقم الجوال',
  address: 'العنوان',
  city: 'المدينة',
  selectCity: 'اختر المدينة',
  notes: 'ملاحظات (اختياري)',
  placeOrder: 'تأكيد الطلب',
  processing: 'جاري المعالجة...',
  orderPlaced: 'تم تأكيد الطلب بنجاح',
  uploadProof: 'رفع إيصال الدفع',
  uploadHint: 'اختر صورة الإيصال من المعرض',
  changePhoto: 'تغيير الصورة',
  camera: 'الكاميرا',
  gallery: 'المعرض',
  cancel: 'إلغاء',
  save: 'حفظ',
  pending: 'قيد الانتظار',
  approved: 'تمت الموافقة',
  preparing: 'قيد التجهيز',
  shipped: 'تم الشحن',
  delivered: 'تم التوصيل',
  cancelled: 'ملغي',
  loading: 'جاري التحميل...',
  error: 'حدث خطأ',
  retry: 'إعادة المحاولة',
  noOrders: 'لا توجد طلبات بعد',
  items: 'عناصر',
  searchOrders: 'بحث في الطلبات',
  filterByStatus: 'تصفية حسب الحالة',
  all: 'الكل',
  reorder: 'إعادة الطلب',
  viewDetails: 'عرض التفاصيل',
  orderSummary: 'ملخص الطلب',
  shippingAddress: 'عنوان الشحن',
  paymentProof: 'إيصال الدفع',
  confirmDelete: 'هل أنت متأكد من الحذف؟',
  yes: 'نعم',
  no: 'لا',
  invalidCode: 'الكود غير صالح',
};

const en: Record<string, string> = {
  cart: 'Cart',
  cartEmpty: 'Your cart is empty',
  startShopping: 'Start Shopping',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  free: 'Free',
  total: 'Total',
  checkout: 'Checkout',
  remove: 'Remove',
  quantity: 'Quantity',
  addToCart: 'Add to Cart',
  buyNow: 'Buy Now',
  favorites: 'Favorites',
  search: 'Search',
  profile: 'Profile',
  orders: 'My Orders',
  orderDetails: 'Order Details',
  orderStatus: 'Order Status',
  orderDate: 'Order Date',
  orderTotal: 'Order Total',
  paymentMethod: 'Payment Method',
  cashOnDelivery: 'Cash on Delivery',
  creditCard: 'Credit Card',
  wallet: 'Digital Wallet',
  transferReceipt: 'Bank Transfer (Receipt)',
  couponCode: 'Coupon Code',
  apply: 'Apply',
  invalidCoupon: 'Invalid coupon code',
  validCoupon: 'Coupon applied',
  discount: 'Discount',
  fullName: 'Full Name',
  phone: 'Phone Number',
  address: 'Address',
  city: 'City',
  selectCity: 'Select City',
  notes: 'Notes (optional)',
  placeOrder: 'Place Order',
  processing: 'Processing...',
  orderPlaced: 'Order placed successfully',
  uploadProof: 'Upload Payment Receipt',
  uploadHint: 'Choose receipt image from gallery',
  changePhoto: 'Change Photo',
  camera: 'Camera',
  gallery: 'Gallery',
  cancel: 'Cancel',
  save: 'Save',
  pending: 'Pending',
  approved: 'Approved',
  preparing: 'Preparing',
  shipped: 'Shipped',
  delivered: 'Delivered',
  cancelled: 'Cancelled',
  loading: 'Loading...',
  error: 'An error occurred',
  retry: 'Retry',
  noOrders: 'No orders yet',
  items: 'items',
  searchOrders: 'Search orders',
  filterByStatus: 'Filter by status',
  all: 'All',
  reorder: 'Reorder',
  viewDetails: 'View Details',
  orderSummary: 'Order Summary',
  shippingAddress: 'Shipping Address',
  paymentProof: 'Payment Receipt',
  confirmDelete: 'Are you sure you want to delete?',
  yes: 'Yes',
  no: 'No',
  invalidCode: 'Invalid code',
  adminDashboard: 'Admin Dashboard',
  admin: 'Admin',
  products: 'Products',
  customers: 'Customers',
  categories: 'Categories',
  coupons: 'Coupons',
  settings: 'Settings',
  totalSales: 'Total Sales',
  totalOrders: 'Total Orders',
  totalProducts: 'Total Products',
  totalUsers: 'Total Users',
  recentOrders: 'Recent Orders',
  viewAll: 'View All',
  addProduct: 'Add Product',
  editProduct: 'Edit Product',
  deleteProduct: 'Delete Product',
  productTitle: 'Title',
  productDescription: 'Description',
  productPrice: 'Price',
  productStock: 'Stock',
  productCategory: 'Category',
  productImage: 'Image URL',
  productFeatured: 'Featured',
  productFlashSale: 'Flash Sale',
  flashSalePrice: 'Flash Sale Price',
  searchProducts: 'Search products',
  noProducts: 'No products found',
  orderSearch: 'Search orders',
  updateStatus: 'Update Status',
  orderDetail: 'Order Detail',
  customer: 'Customer',
  addCategory: 'Add Category',
  editCategory: 'Edit Category',
  categoryName: 'Name',
  categoryNameAr: 'Arabic Name',
  categoryImage: 'Image URL',
  noCategories: 'No categories',
  addCoupon: 'Add Coupon',
  editCoupon: 'Edit Coupon',
  discountPercent: 'Discount %',
  maxUses: 'Max Uses',
  currentUses: 'Current Uses',
  minPurchase: 'Min Purchase',
  expiresAt: 'Expires At',
  active: 'Active',
  inactive: 'Inactive',
  noCoupons: 'No coupons',
  addCity: 'Add City',
  editCity: 'Edit City',
  cityName: 'Name',
  cityNameAr: 'Arabic Name',
  shippingFee: 'Shipping Fee',
  deliveryDays: 'Delivery Days',
  noCities: 'No cities',
  searchCustomers: 'Search customers',
  noCustomers: 'No customers',
  promoteToAdmin: 'Promote to Admin',
  demoteToCustomer: 'Demote to Customer',
  role: 'Role',
  joinedAt: 'Joined At',
  confirmDeleteTitle: 'Confirm Delete',
  confirmDeleteMessage: 'Are you sure you want to delete this item?',
  edit: 'Edit',
  delete: 'Delete',
  create: 'Create',
  update: 'Update',
  sar: 'SAR',
  orderId: 'Order ID',
  status: 'Status',
  createdAt: 'Created',
  viewReceipt: 'View Receipt',
  contactWhatsApp: 'Contact via WhatsApp',
  adminOnly: 'Admin Only',
  superAdminOnly: 'Super Admin Only',
  permissionDenied: 'Permission Denied',
  sarSymbol: 'ريال',
  stats: 'Statistics',
  quickActions: 'Quick Actions',
  productManagement: 'Product Management',
  orderManagement: 'Order Management',
  categoryManagement: 'Category Management',
  couponManagement: 'Coupon Management',
  customerManagement: 'Customer Management',
  shippingManagement: 'Shipping Management',
  totalDiscount: 'Total Discount',
  totalCouponDiscount: 'Coupon Discount',
  weeklySales: 'Weekly Sales',
  latestOrders: 'Latest Orders',
  searchByName: 'Search by name...',
  searchByOrder: 'Search by order ID or customer...',
  orderStatusUpdated: 'Order status updated successfully',
  productDeleted: 'Product deleted successfully',
  categoryDeleted: 'Category deleted successfully',
  couponDeleted: 'Coupon deleted successfully',
  cityDeleted: 'City deleted successfully',
  roleUpdated: 'User role updated successfully',
};

type Locale = 'ar' | 'en';

let currentLocale: Locale = 'ar';

const translations: Record<Locale, Record<string, string>> = { ar, en };

export function setLocale(locale: Locale) {
  currentLocale = locale;
}

export function t(key: string): string {
  return translations[currentLocale]?.[key] || translations['ar']?.[key] || key;
}

export function getLocale(): Locale {
  return currentLocale;
}
